#!/usr/bin/env bash
set -euo pipefail

MODE="dry-run"
TARGET_DIR="."
PROJECT_TYPE="auto"
ENABLE_TAKUMI="no"
ENABLE_GITHUB_ACTIONS="yes"
ENABLE_IGNORE_SCRIPTS="yes"
BACKUP_DIR=""

usage() {
  cat <<USAGE
Usage:
  $(basename "$0") [--apply] [--type auto|node|python|go|rust] [--dir PATH] [--takumi yes|no] [--gha yes|no] [--ignore-scripts yes|no]

Examples:
  $(basename "$0") --type auto
  $(basename "$0") --apply --type node --takumi yes
  $(basename "$0") --apply --dir /path/to/project --type python
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --apply) MODE="apply"; shift ;;
    --type) PROJECT_TYPE="$2"; shift 2 ;;
    --dir) TARGET_DIR="$2"; shift 2 ;;
    --takumi) ENABLE_TAKUMI="$2"; shift 2 ;;
    --gha) ENABLE_GITHUB_ACTIONS="$2"; shift 2 ;;
    --ignore-scripts) ENABLE_IGNORE_SCRIPTS="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1"; usage; exit 1 ;;
  esac
done

[[ -d "$TARGET_DIR" ]] || { echo "Target directory not found: $TARGET_DIR"; exit 1; }
cd "$TARGET_DIR"

say() { printf "%s\n" "$1"; }
backup_file() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  mkdir -p "$BACKUP_DIR"
  cp -a "$f" "$BACKUP_DIR/$(basename "$f").bak"
}
write_if_apply() {
  local path="$1"
  local tmp="$2"
  if [[ "$MODE" == "apply" ]]; then
    mkdir -p "$(dirname "$path")"
    backup_file "$path"
    cp "$tmp" "$path"
    say "[APPLY] wrote $path"
  else
    say "[DRY-RUN] would write $path"
  fi
}

if [[ "$PROJECT_TYPE" == "auto" ]]; then
  if [[ -f package.json ]]; then PROJECT_TYPE="node"
  elif [[ -f pyproject.toml || -f requirements.txt || -f Pipfile ]]; then PROJECT_TYPE="python"
  elif [[ -f go.mod ]]; then PROJECT_TYPE="go"
  elif [[ -f Cargo.toml ]]; then PROJECT_TYPE="rust"
  else PROJECT_TYPE="common"
  fi
fi

BACKUP_DIR=".supplychain-tool-backup-$(date +%Y%m%d-%H%M%S)"
say "Target: $(pwd)"
say "Mode: $MODE"
say "Detected/selected type: $PROJECT_TYPE"

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

create_node_files() {
  local npmrc="$TMPDIR/.npmrc"
  {
    echo "# Generated by supplychain-install-helper.sh"
    echo "min-release-age=7"
    echo "fetch-retry-factor=2"
    echo "fetch-retry-mintimeout=20000"
    echo "fetch-retry-maxtimeout=120000"
    if [[ "$ENABLE_TAKUMI" == "yes" ]]; then
      echo "registry=https://npm.flatt.tech/"
    fi
    if [[ "$ENABLE_IGNORE_SCRIPTS" == "yes" ]]; then
      echo "ignore-scripts=true"
    else
      echo "ignore-scripts=false"
    fi
    echo "audit=true"
  } > "$npmrc"
  write_if_apply ".npmrc" "$npmrc"

  if [[ "$ENABLE_GITHUB_ACTIONS" == "yes" ]]; then
    local gha="$TMPDIR/supply-chain-security.yml"
    {
      echo "name: Supply Chain Security Checks"
      echo
      echo "on: [push, pull_request]"
      echo
      echo "jobs:"
      echo "  supply-chain:"
      echo "    runs-on: ubuntu-latest"
      echo "    permissions:"
      echo "      id-token: write"
      echo "    steps:"
      echo "      - uses: actions/checkout@v4"
      if [[ "$ENABLE_TAKUMI" == "yes" ]]; then
        echo "      - name: Setup Takumi Guard (npm)"
        echo "        uses: flatt-security/setup-takumi-guard-npm@v1"
      fi
      echo "      - name: Install dependencies"
      echo "        run: npm ci"
      echo "      - name: Audit npm dependencies"
      echo "        run: npm audit --audit-level=moderate"
    } > "$gha"
    write_if_apply ".github/workflows/supply-chain-security.yml" "$gha"
  fi
}

create_python_files() {
  if [[ -f pyproject.toml ]]; then
    say "[INFO] pyproject.toml exists; automatic in-place merge is not attempted to avoid breaking syntax."
    say "[INFO] Suggested snippet:"
    cat <<'PY'
[[tool.poetry.source]]
name = "takumi-guard"
url = "https://pypi.flatt.tech/"
priority = "primary"

[[tool.poetry.source]]
name = "pypi"
url = "https://pypi.org/simple"
priority = "secondary"
PY
  fi

  if [[ -f requirements.txt ]]; then
    local req="$TMPDIR/requirements.txt"
    if [[ "$ENABLE_TAKUMI" == "yes" ]]; then
      echo "-i https://pypi.flatt.tech/" > "$req"
    else
      echo "# Keep your current index if you do not use Takumi Guard" > "$req"
    fi
    cat requirements.txt >> "$req"
    write_if_apply "requirements.txt" "$req"
  else
    local reqnew="$TMPDIR/requirements.txt"
    if [[ "$ENABLE_TAKUMI" == "yes" ]]; then
      echo "-i https://pypi.flatt.tech/" > "$reqnew"
    else
      echo "# Add your Python dependencies below" > "$reqnew"
    fi
    write_if_apply "requirements.txt" "$reqnew"
  fi

  if [[ "$ENABLE_GITHUB_ACTIONS" == "yes" ]]; then
    local gha="$TMPDIR/supply-chain-security.yml"
    {
      echo "name: Python Supply Chain Security Checks"
      echo
      echo "on: [push, pull_request]"
      echo
      echo "jobs:"
      echo "  supply-chain:"
      echo "    runs-on: ubuntu-latest"
      echo "    steps:"
      echo "      - uses: actions/checkout@v4"
      echo "      - uses: actions/setup-python@v5"
      echo "        with:"
      echo "          python-version: '3.11'"
      echo "      - name: Install tools"
      echo "        run: pip install guarddog safety"
      echo "      - name: Scan requirements"
      echo "        run: |"
      echo "          test -f requirements.txt && guarddog depscan requirements.txt || true"
      echo "          safety check -r requirements.txt || true"
    } > "$gha"
    write_if_apply ".github/workflows/supply-chain-security.yml" "$gha"
  fi
}

create_go_files() {
  if [[ "$ENABLE_GITHUB_ACTIONS" == "yes" ]]; then
    local gha="$TMPDIR/supply-chain-security.yml"
    {
      echo "name: Go Supply Chain Security Checks"
      echo "on: [push, pull_request]"
      echo "jobs:"
      echo "  supply-chain:"
      echo "    runs-on: ubuntu-latest"
      echo "    steps:"
      echo "      - uses: actions/checkout@v4"
      echo "      - uses: actions/setup-go@v5"
      echo "        with:"
      echo "          go-version: '1.24'"
      echo "      - name: Verify modules"
      echo "        run: |"
      echo "          go mod tidy"
      echo "          go mod verify"
      echo "      - name: Install and run gosec"
      echo "        run: |"
      echo "          go install github.com/securego/gosec/v2/cmd/gosec@latest"
      echo "          \$(go env GOPATH)/bin/gosec ./..."
    } > "$gha"
    write_if_apply ".github/workflows/supply-chain-security.yml" "$gha"
  fi
}

create_rust_files() {
  if [[ "$ENABLE_GITHUB_ACTIONS" == "yes" ]]; then
    local gha="$TMPDIR/supply-chain-security.yml"
    {
      echo "name: Rust Supply Chain Security Checks"
      echo "on: [push, pull_request]"
      echo "jobs:"
      echo "  supply-chain:"
      echo "    runs-on: ubuntu-latest"
      echo "    steps:"
      echo "      - uses: actions/checkout@v4"
      echo "      - name: Install cargo-audit"
      echo "        run: cargo install cargo-audit"
      echo "      - name: Audit"
      echo "        run: cargo audit"
    } > "$gha"
    write_if_apply ".github/workflows/supply-chain-security.yml" "$gha"
  fi
}

case "$PROJECT_TYPE" in
  node) create_node_files ;;
  python) create_python_files ;;
  go) create_go_files ;;
  rust) create_rust_files ;;
  common)
    say "[INFO] Could not detect a specific language project. Only general guidance applies."
    ;;
  *) echo "Unsupported type: $PROJECT_TYPE"; exit 1 ;;
esac

cat <<NEXT

Done.
Next steps:
  1) Review changes (or dry-run output)
  2) Apply if you are satisfied:
       ./$(basename "$0") --apply --type $PROJECT_TYPE --takumi $ENABLE_TAKUMI --gha $ENABLE_GITHUB_ACTIONS --ignore-scripts $ENABLE_IGNORE_SCRIPTS
  3) Re-check:
       ./supplychain-check.sh .
  4) Commit the result:
       git add . && git commit -m "Add supply chain security baseline"
NEXT
